app/dictionary/routes.py
from flask import Blueprint, flash, redirect, render_template, current_app, request, url_for
from flask_login import LoginManager, login_required, logout_user, current_user, login_user

from app.utilities.video_utils import *
from app.utilities.file_system_utils import *

from app.extensions.plotly_pose_data import plotly_pose_figure
from app.extensions.plotly_pose_contact_points import plotly_pose_contact_points

import json
import pandas as pd
import plotly
import pytz
import random

bp = Blueprint("dictionary", __name__, url_prefix="/dictionary")
tz = pytz.timezone('UTC')


@bp.route('/search', methods=['GET'])
def pose_search():
    title = "Explore Pole Shapes"
    data = pd.read_csv(os.path.join(
        'app', 'static', 'dictionary', 'tricks', 'pose_data.csv'))
    pose_names = data['pose_name'].unique()
    total_poses = len(pose_names)
    query = request.args.get('q', '')
    filepath_src = 'dictionary/tricks/'
    if query:
        filtered_data = data[data['pose_name'].str.contains(
            query, case=False, na=False)]
        results = filtered_data.to_dict(orient='records')
    else:
        results = data.sample(n=5, random_state=random.randint(
            1, len(data))).to_dict(orient='records')

    return render_template("dictionary/tricks/search.html", results=results, title=title, pose_names=pose_names, total_poses=total_poses, filepath_src=filepath_src)


@bp.route('/detail/<pose_name>', methods=['GET'])
def pose_detail_page(pose_name):
    if_spine = request.args.get('spine', 'true').lower() == 'true'
    if_right_arm = request.args.get('right_arm', 'false').lower() == 'true'
    if_left_arm = request.args.get('left_arm', 'false').lower() == 'true'
    if_right_leg = request.args.get('right_leg', 'false').lower() == 'true'
    if_left_leg = request.args.get('left_leg', 'false').lower() == 'true'
    data = pd.read_csv(os.path.join(
        'app', 'static', 'dictionary', 'tricks', 'pose_data.csv'))
    filtered_data = data[data['pose_name'] == pose_name]
    image_filename = 'dictionary/tricks/' + \
        filtered_data['image_filename'].values[0]
    fig = plotly_pose_figure(filtered_data, 0, spine=if_spine, right_arm=if_right_arm,
                             left_arm=if_left_arm, right_leg=if_right_leg, left_leg=if_left_leg)
    fig_plot = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)
    return render_template("dictionary/tricks/detail_plot_figure.html", fig_plot=fig_plot, title=pose_name, image_filename=image_filename)


@bp.route('/detail/<pose_name>/points', methods=['GET'])
def pose_detail_contact_points(pose_name):
    data = pd.read_csv(os.path.join(
        'app', 'static', 'dictionary', 'tricks', 'pose_data.csv'))
    filtered_data = data[data['pose_name'] == pose_name]
    image_filename = 'dictionary/tricks/' + \
        filtered_data['image_filename'].values[0]
    fig = plotly_pose_contact_points(filtered_data, 0)
    fig_plot = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)
    return render_template("dictionary/tricks/detail_plot_contacts.html", fig_plot=fig_plot, title=pose_name, image_filename=image_filename)


@bp.route('/search/legs', methods=['GET'])
def pose_legs_search():
    title = "Explore Leg Positions"
    data = pd.read_csv(os.path.join(
        'app', 'static', 'dictionary', 'positions', 'legs', 'pose_data.csv'))
    pose_names = data['pose_name'].unique()
    total_poses = len(pose_names)
    query = request.args.get('q', '')
    filepath_src = 'dictionary/positions/legs/'
    if query:
        filtered_data = data[data['pose_name'].str.contains(
            query, case=False, na=False)]
        results = filtered_data.to_dict(orient='records')
    else:
        results = data.sample(n=5, random_state=random.randint(
            1, len(data))).to_dict(orient='records')
    return render_template("dictionary/legs/search.html", results=results, title=title, pose_names=pose_names,
                           total_poses=total_poses, filepath_src=filepath_src)


@bp.route('/detail/legs/<pose_name>', methods=['GET'])
def pose_legs_detail_page(pose_name):
    if_spine = request.args.get('spine', 'false').lower() == 'true'
    if_right_arm = request.args.get('right_arm', 'false').lower() == 'true'
    if_left_arm = request.args.get('left_arm', 'false').lower() == 'true'
    if_right_leg = request.args.get('right_leg', 'true').lower() == 'true'
    if_left_leg = request.args.get('left_leg', 'true').lower() == 'true'
    data = pd.read_csv(os.path.join(
        'app', 'static', 'dictionary', 'positions', 'legs', 'pose_data.csv'))
    filtered_data = data[data['pose_name'] == pose_name]
    image_filename = 'dictionary/positions/legs/' + \
        filtered_data['image_filename'].values[0]
    fig = plotly_pose_figure(filtered_data, 0, spine=if_spine, right_arm=if_right_arm,
                             left_arm=if_left_arm, right_leg=if_right_leg, left_leg=if_left_leg)
    fig_plot = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)
    return render_template("dictionary/legs/detail_plot_figure.html", fig_plot=fig_plot, title=pose_name, image_filename=image_filename)


@bp.route('/detail/legs/<pose_name>/points', methods=['GET'])
def pose_legs_detail_contact_points(pose_name):
    data = pd.read_csv(os.path.join(
        'app', 'static', 'dictionary', 'positions', 'legs', 'pose_data.csv'))
    filtered_data = data[data['pose_name'] == pose_name]
    image_filename = 'dictionary/positions/legs/' + \
        filtered_data['image_filename'].values[0]
    fig = plotly_pose_contact_points(filtered_data, 0)
    fig_plot = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)
    return render_template("dictionary/legs/detail_plot_contacts.html", fig_plot=fig_plot, title=pose_name, image_filename=image_filename)

@bp.route('/search/grip', methods=['GET'])
def pose_grip_search():
    title = "Explore Grip Positions"
    data = pd.read_csv(os.path.join('app', 'static', 'dictionary', 'positions', 'grip', 'pose_data.csv'))
    data = data[~data['pose_name'].str.contains('-inv')]
    pose_names = data['pose_name'].unique()
    total_poses = len(pose_names)
    query = request.args.get('q', '')
    filepath_src = 'dictionary/positions/grip/'
    if query:
        filtered_data = data[data['pose_name'].str.contains(query, case=False, na=False)]
        filtered_data = filtered_data[~filtered_data['pose_name'].str.contains('-inv')]
        results = filtered_data.to_dict(orient='records')
    else:
        results = data.sample(n=5, random_state=random.randint(
            1, len(data))).to_dict(orient='records')
    return render_template("dictionary/grip/search.html", results=results, title=title, pose_names=pose_names,
                           total_poses=total_poses, filepath_src=filepath_src)


@bp.route('/detail/grip/<pose_name>', methods=['GET'])
def pose_grip_detail_page(pose_name):
    if_spine = request.args.get('spine', 'false').lower() == 'true'
    if_right_arm = request.args.get('right_arm', 'true').lower() == 'true'
    if_left_arm = request.args.get('left_arm', 'true').lower() == 'true'
    if_right_leg = request.args.get('right_leg', 'false').lower() == 'true'
    if_left_leg = request.args.get('left_leg', 'false').lower() == 'true'
    data = pd.read_csv(os.path.join(
        'app', 'static', 'dictionary', 'positions', 'grip', 'pose_data.csv'))
    filtered_data = data[~data['pose_name'].str.contains('-inv')]
    image_filename = 'dictionary/positions/grip/' + \
        filtered_data['image_filename'].values[0]
    fig = plotly_pose_figure(filtered_data, 0, spine=if_spine, right_arm=if_right_arm,
                             left_arm=if_left_arm, right_leg=if_right_leg, left_leg=if_left_leg)
    fig_plot = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)
    return render_template("dictionary/grip/detail_plot_figure.html", fig_plot=fig_plot, title=pose_name, image_filename=image_filename)


@bp.route('/detail/grip/<pose_name>/points', methods=['GET'])
def pose_grip_detail_contact_points(pose_name):
    data = pd.read_csv(os.path.join(
        'app', 'static', 'dictionary', 'positions', 'grip', 'pose_data.csv'))
    filtered_data = data[~data['pose_name'].str.contains('-inv')]
    image_filename = 'dictionary/positions/grip/' + \
        filtered_data['image_filename'].values[0]
    fig = plotly_pose_contact_points(filtered_data, 0)
    fig_plot = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)
    return render_template("dictionary/grip/detail_plot_contacts.html", fig_plot=fig_plot, title=pose_name, image_filename=image_filename)

app/templates/dictionary/tricks/detail_plot_contacts.html
{% extends '_base.html' %}
{% block content %}
<p class="mt-5 text-start">
    <a href="{{ url_for('dictionary.pose_search') }}"
        class="badge align-items-center p-1 pe-2 text-secondary-emphasis bg-secondary-subtle border border-secondary-subtle rounded-pill"
        style="text-decoration: none;">
        🔍 Back to Search</a>
</p>

<h1 class="text-start text-primary">{{ title }}</h1>
<p class="text-start">Grasp the pole with one hand while leaning back and supporting your weight on the extended
    opposite arm, bringing one knee to your chest and resting your chin thoughtfully on your knee, reminiscent of
    Rodin's 'The Thinker' statue.</p>
<p class="text-start">

    <a href="{{ url_for('dictionary.pose_detail_page', pose_name=title) }}" class="btn btn-sm btn-outline-secondary">
        View Pole Shape Trends
    </a>


    <a href="javascript:void(0);" onclick="openImageWindow('{{ url_for('static', filename=image_filename) }}');"
        class="btn btn-sm btn-outline-secondary">
        View Original Image
    </a>


</p>


<div class="col-md-12">
    <div id="fig_plot" style="border: 2px solid silver; border-radius: 15px; overflow: hidden;">

        <script>
            var fig_plot = {{ fig_plot | safe }};
            Plotly.newPlot('fig_plot', fig_plot);

            function resizePlot() {
                var graphContainer = document.getElementById('fig_plot');
                var width = graphContainer.offsetWidth; // Get the current width
                var update = {
                    height: width // Set height equal to width
                };
                Plotly.relayout('fig_plot', update);
            }

            window.onload = resizePlot;
            window.onresize = resizePlot;

            function updatePlot() {
                var queryParams = '?spine=' + document.getElementById('check_spine').checked;
                queryParams += '&right_arm=' + document.getElementById('check_right_arm').checked;
                queryParams += '&left_arm=' + document.getElementById('check_left_arm').checked;
                queryParams += '&right_leg=' + document.getElementById('check_right_leg').checked;
                queryParams += '&left_leg=' + document.getElementById('check_left_leg').checked;

                var currentUrl = window.location.href;
                var baseUrl = currentUrl.split('?')[0];  // Get the base URL without query parameters
                window.location.href = baseUrl + queryParams;
            }

            function openImageWindow(imageUrl) {
                window.open(imageUrl, 'newwindow', 'width=600,height=400');
                return false;
            }
        </script>


    </div>
</div>

{% endblock %}

app/templates/dictionary/tricks/detail_plot_figure.html
{% extends '_base.html' %}
{% block content %}

{% if request.path == '/legs' %}

<p class="mt-5 text-start">
    <a href="{{ url_for('dictionary.pose_legs_search') }}"
      class="badge align-items-center p-1 pe-2 text-secondary-emphasis bg-secondary-subtle border border-secondary-subtle rounded-pill"
      style="text-decoration: none;">
      🔍 Back to Search</a>
  </p>
  {% else %}

<p class="mt-5 text-start">
    <a href="{{ url_for('dictionary.pose_search') }}"
      class="badge align-items-center p-1 pe-2 text-secondary-emphasis bg-secondary-subtle border border-secondary-subtle rounded-pill"
      style="text-decoration: none;">
      🔍 Back to Search</a>
  </p>
  {% endif %}

<h1 class="text-start text-primary">{{ title }}</h1>
<p class="text-start">Grasp the pole with one hand while leaning back and supporting your weight on the extended
    opposite arm, bringing one knee to your chest and resting your chin thoughtfully on your knee, reminiscent of
    Rodin's 'The Thinker' statue.</p>

<p class="text-start">
    <a href="{{ url_for('dictionary.pose_detail_contact_points', pose_name=title) }}" class="btn btn-sm btn-outline-secondary">
        View Contact Points
    </a>
    <a href="javascript:void(0);" onclick="openImageWindow('{{ url_for('static', filename=image_filename) }}');"
        class="btn btn-sm btn-outline-secondary">
        View Original Image
    </a>

</p>
<div>
    <div class="row p-3">
        <div class="col mt-1">
            <input class="form-check-input" type="checkbox" value="" id="check_spine">
            <label class="form-check-label" for="flexCheckDefault">Spine</label>
        </div>
        <div class="col mt-1">
            <input class="form-check-input" type="checkbox" value="" id="check_right_arm">
            <label class="form-check-label" for="flexCheckDefault">R.Arm</label>
        </div>
        <div class="col mt-1">
            <input class="form-check-input" type="checkbox" value="" id="check_left_arm">
            <label class="form-check-label" for="flexCheckDefault">L.Arm</label>
        </div>
        <div class="col mt-1">
            <input class="form-check-input" type="checkbox" value="" id="check_right_leg">
            <label class="form-check-label" for="flexCheckDefault">R.Leg</label>
        </div>
        <div class="col mt-1">
            <input class="form-check-input" type="checkbox" value="" id="check_left_leg">
            <label class="form-check-label" for="flexCheckDefault">L.Leg</label>
        </div>
        <div class="col">
            <button type="submit" class="btn w-100 btn-primary" onclick="updatePlot()">Update</button>

        </div>
    </div>
</div>

<div class="col-md-12">
    <div id="fig_plot" style="border: 2px solid silver; border-radius: 15px; overflow: hidden;">

        <script>
            var fig_plot = {{ fig_plot | safe }};
            Plotly.newPlot('fig_plot', fig_plot);

            function resizePlot() {
                var graphContainer = document.getElementById('fig_plot');
                var width = graphContainer.offsetWidth; // Get the current width
                var update = {
                    height: width // Set height equal to width
                };
                Plotly.relayout('fig_plot', update);
            }

            window.onload = resizePlot;
            window.onresize = resizePlot;

            function updatePlot() {
                var queryParams = '?spine=' + document.getElementById('check_spine').checked;
                queryParams += '&right_arm=' + document.getElementById('check_right_arm').checked;
                queryParams += '&left_arm=' + document.getElementById('check_left_arm').checked;
                queryParams += '&right_leg=' + document.getElementById('check_right_leg').checked;
                queryParams += '&left_leg=' + document.getElementById('check_left_leg').checked;

                var currentUrl = window.location.href;
                var baseUrl = currentUrl.split('?')[0];  // Get the base URL without query parameters
                window.location.href = baseUrl + queryParams;
            }

            function openImageWindow(imageUrl) {
                window.open(imageUrl, 'newwindow', 'width=600,height=400');
                return false;
            }
        </script>


    </div>
</div>

{% endblock %}

app/templates/dictionary/tricks/search.html
{% extends '_base.html' %}
{% block content %}

<div class="row">
    <div class="col-12">
        <p class="lead mt-5 text-start"><b>{{ title }}</b> | {{ total_poses }} entries</p>
    </div>
    <div class="col-12">
        <form method="GET" action="{{ url_for('dictionary.pose_search') }}">
            <div class="row">
                <div class="col-8">
                    <input class="form-control" type="search" list="datalistOptions" name="q" id="PoseSearch"
                        placeholder="Hover to see options...">
                    <datalist id="datalistOptions">
                        {% for pose_name in pose_names %}
                        <option value="{{ pose_name }}">

                        </option>
                        {% endfor %}
                    </datalist>
                </div>

                <div class="col-4">
                    <button type="submit" class="btn w-100 btn-primary">Search</button>
                </div>
            </div>
        </form>
    </div>

</div>

<hr />

<div class="row" style="min-height: 50vh;">

    {% if results %}

    <ol class="list-group list-group-numbered" style="--bs-gutter-x: 0!important;">
        {% for row in results %}
        <li class="list-group-item d-flex">
            <div class="col-8 text-start">
                <div class="fw-bold mb-2" style="padding-left:1em">
                    <a href="{{ url_for('dictionary.pose_detail_page', pose_name=row['pose_name']) }}"
                        class="link-primary">
                        {{row['pose_name'] }}</a>
                </div>
                <p style="padding-left: 1em">


                    <a href="{{ url_for('dictionary.pose_detail_contact_points', pose_name=row['pose_name']) }}"
                        class="btn btn-sm btn-outline-secondary">View Contact Points</a>
                    <a href="{{ url_for('dictionary.pose_detail_page', pose_name=row['pose_name']) }}"
                        class="btn btn-sm btn-outline-secondary">View Pose Shape</a>

                </p>
            </div>
            <div class="col-4 text-end">
                <img src="{{ url_for('static', filename='dictionary/tricks/' ~ row['image_filename']) }}"
                    class="img-fluid" style="max-height:75px;" />

            </div>
        </li>
        {% endfor %}
    </ol>



    {% endif %}

    <small class="mt-5 text-secondary">Credits: Images are sourced from <a
            href="https://books.google.de/books/about/Pole_Dance_Fitness.html?id=G1UqtAEACAAJ&redir_esc=y"
            class="text-secondary" target="_blank">Irina Kartaly's Pole Dance Fitness</a></small>

</div>
{% endblock %}