app/models/report.py
from app import db
import uuid
from datetime import datetime, timedelta

class VideoReport(db.Model):
    __tablename__ = 'reports'
    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    author_id = db.Column(db.String(36), db.ForeignKey('users.id'), nullable=False)
    video_id = db.Column(db.String(36), db.ForeignKey('videos.id'), nullable=False)
    spin_count = db.Column(db.String(100))
    inversion_count = db.Column(db.String(1000), nullable=True)
    detected_tricks = db.Column(db.String(1000), nullable=True)
    detected_grip = db.Column(db.String(1000), nullable=True)
    detected_legs = db.Column(db.String(1000), nullable=True)
    created_on = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    deleted = db.Column(db.Boolean, default=False)
    deleted_on = db.Column(db.DateTime, nullable=True)
    scheduled_for_deletion_on = db.Column(db.DateTime, nullable=True)
    video_post = db.relationship('VideoPost', foreign_keys=[video_id], backref='reports', lazy=True)

    def __repr__(self):
        return '<Report {}>'.format(self.id)
    

app/api/routes.py
from flask import Blueprint, send_from_directory, current_app, render_template, send_from_directory, redirect, url_for
from flask_login import login_required, current_user
import os
import pandas as pd
import pytz


bp = Blueprint("api", __name__, url_prefix="/api/v1/")
tz = pytz.timezone('UTC')

@bp.route('/uploads/<author_id>/<id>')
@login_required
def serve_uploaded_video(author_id,id):
    filename = f'{id}.mp4'
    filepath = os.path.join(current_app.config['SERVE_UPLOAD_FOLDER'],author_id)
    return send_from_directory(filepath,filename)

@bp.route('/dictionary/<category>')
@login_required
def serve_static_dictionary_tricks(category):
    if category == 'tricks':
        dict_read = pd.read_csv(os.path.join('app','static', 'dictionary', 'tricks', 'pose_data.csv'))
        dict_data = dict_read.to_dict(orient='records')
    elif category == 'legs':
        dict_read = pd.read_csv(os.path.join('app','static', 'dictionary', 'positions','legs', 'pose_data.csv'))
        dict_data = dict_read.to_dict(orient='records')
    elif category == 'body':
        dict_read = pd.read_csv(os.path.join('app','static', 'dictionary', 'positions','body', 'pose_data.csv'))
        dict_data = dict_read.to_dict(orient='records')
    elif category == 'grip':
        dict_read = pd.read_csv(os.path.join('app','static', 'dictionary', 'positions','grip', 'pose_data.csv'))
        dict_data = dict_read.to_dict(orient='records')
    else:
        return redirect(url_for('diary.all_dance_entries'))
    return dict_data

@bp.route('/processed/<author_id>/<id>')
@login_required
def serve_video_cover_page(author_id,id):
    if current_user.is_authenticated and current_user.id == author_id:
        filename = '0000_00000000.png'
        filepath = os.path.join(current_app.config['SERVE_PROCESSED_FOLDER'],author_id,id,'annotated')
        return send_from_directory(filepath,filename)
    

@bp.route('/processed/<author_id>/<id>/timeline')
@login_required
def serve_timeline_image(author_id,id):
    if current_user.is_authenticated and current_user.id == author_id:
        filename = 'timeline.png'
        filepath = os.path.join(current_app.config['SERVE_PROCESSED_FOLDER'],author_id,id,'annotated')
        return send_from_directory(filepath,filename)
    
@bp.route('/processed/<author_id>/<id>/<image_filename>')
@login_required
def serve_annotated_frame_img(author_id,id, image_filename):
    if current_user.is_authenticated and current_user.id == author_id:
        filepath = os.path.join(current_app.config['SERVE_PROCESSED_FOLDER'],author_id,id,'annotated')
        return send_from_directory(filepath,image_filename)
               

@bp.route('/pdata/<author_id>/<id>')
@login_required
def serve_pose_data(author_id,id):
    if current_user.is_authenticated and current_user.id == author_id:
        filename = 'pose_data.csv'
        filepath = os.path.join(current_app.config['SERVE_PROCESSED_FOLDER'],author_id,id)
        return send_from_directory(filepath,filename)

app/reports/routes.py
from flask import Blueprint, render_template, current_app, flash, redirect, url_for
from flask_login import login_required, current_user

from app.extensions.db import db
from app.extensions.plotly_visualizations import generate_histogram_chart, generate_histogram_chart_horizontal
from app.extensions.plotly_pose_animation import plotly_dynamic_pose_figure
from app.extensions.plotly_polar_plot import plot_polar_angles
from app.extensions.plotly_dance_timeline import plotly_visualize_timeline
from app.models import VideoPost, VideoReport
from app.services.pose_dimension_calculator import PoseDimensionCalculator
from app.services.pose_spatial_classifier import PoseSpatialClassifier
from app.services.pose_sequence_analyzer import PoseSequenceAnalyzer
from app.extensions.generate_timeline_visual import generate_timeline_image
from app.utilities.static_files import load_reference_data

import os
from datetime import datetime
import json
import pandas as pd
import plotly
import plotly.express as px
import pytz

bp = Blueprint("reports", __name__, url_prefix="/reports")
tz = pytz.timezone('UTC')

def process_pose_data(source_path, save_path, video_post, tricks, ref_body, ref_legs, ref_grip):
    with open(source_path, 'r') as file:
        pd_read = pd.read_csv(file)
    pd_calculated = PoseDimensionCalculator(pd_read, is_video=True)
    pd_classified = PoseSpatialClassifier(
        pd_calculated.data, ref_body, ref_legs, ref_grip)
    results = PoseSequenceAnalyzer(pd_classified.data, tricks)
    pd_results = results.data
    print("inversion count", results.inversion_count)

    if len(pd_results) > 0:
        pd_results.to_csv(save_path, index=False)
        video_post.is_calculated = True

        top_tricks = pd_results[pd_results['pos_trick'] != 'undefined']['pos_trick'].value_counts().nlargest(3).index.tolist()
        top_legs = pd_results[pd_results['pos_legs'] != 'undefined']['pos_legs'].value_counts().nlargest(3).index.tolist()
        top_grip = pd_results[pd_results['pos_grip'] != 'undefined']['pos_grip'].value_counts().nlargest(3).index.tolist()

        new_report = VideoReport(
            author_id=video_post.author_id,
            video_id=video_post.id,
            spin_count=str(results.spin_count),
            inversion_count=str(results.inversion_count),
            detected_tricks=','.join(top_tricks),
            detected_legs=','.join(top_legs),
            detected_grip=','.join(top_grip),
            created_on=datetime.utcnow()
        )

        db.session.add(video_post)
        db.session.add(new_report)
        db.session.commit()

        return pd_results
    else:
        return None


@bp.route("/<id>/", methods=["GET", "POST"])
@login_required
def overview(id):
    video_post = VideoPost.query.get_or_404(id)
    if not video_post.is_calculated:
        tricks, ref_body, ref_legs, ref_grip = load_reference_data()
        pd_filepath = os.path.join(current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'pose_data_raw.csv')
        pd_savepath = os.path.join(current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'pose_data.csv')
        pd_results = process_pose_data(pd_filepath, pd_savepath, video_post, tricks, ref_body, ref_legs, ref_grip)        
        annotated_dir = os.path.join(current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'annotated')
        generate_timeline_image(annotated_dir, pd_results)        
        timeline_image = generate_timeline_image(annotated_dir, pd_results)
        
        if timeline_image:
            print("timeline image generated")
            
        if pd_results is None:
            flash("Something went wrong")
            return redirect(url_for('diary.all_dance_entries'))
        else:
            return redirect(url_for('reports.overview', id=video_post.id))
    else:
        video_report = VideoReport.query.filter_by(video_id=video_post.id, author_id=video_post.author_id).first()
        
        if video_post.report_id is None:
            video_post.report_id = video_report.id
            db.session.commit()
        
        if not video_report:
            flash("Report not found")
            return redirect(url_for('diary.all_dance_entries'))

        pd_filepath = os.path.join(
            current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'pose_data.csv')
        with open(pd_filepath, 'r') as file:
            pd_results = pd.read_csv(file)
            
    fig_timeline = plotly_visualize_timeline(pd_results, video_report.created_on, video_report, 0.12)
    fig_plot = json.dumps(fig_timeline, cls=plotly.utils.PlotlyJSONEncoder)

    pd_data = pd_results.to_dict(orient='records')

    return render_template("report.html", title=f"{video_post.title}",
                           video_post=video_post,
                           pd_data=pd_data,
                           video_report=video_report,
                           fig_plot=fig_plot,
                           pd_filepath=pd_filepath
                           )


def generate_charts(pd_results, duration):
    fig_body = generate_histogram_chart(pd_results, 'pos_body', duration)
    fig_body_hbar = json.dumps(fig_body, cls=plotly.utils.PlotlyJSONEncoder)
    fig_grip = generate_histogram_chart_horizontal(
        pd_results, 'pos_grip', duration)
    fig_grip_hbar = json.dumps(fig_grip, cls=plotly.utils.PlotlyJSONEncoder)
    fig_legs = generate_histogram_chart_horizontal(
        pd_results, 'pos_legs', duration)
    fig_legs_hbar = json.dumps(fig_legs, cls=plotly.utils.PlotlyJSONEncoder)
    fig_tricks = generate_histogram_chart_horizontal(
        pd_results, 'pos_trick', duration)
    fig_tricks_hbar = json.dumps(
        fig_tricks, cls=plotly.utils.PlotlyJSONEncoder)

    return {
        'fig_body_hbar': fig_body_hbar,
        'fig_legs_hbar': fig_legs_hbar,
        'fig_grip_hbar': fig_grip_hbar,
        'fig_tricks_hbar': fig_tricks_hbar
    }


@bp.route("/<id>/checker", methods=["GET", "POST"])
@login_required
def report_checker(id):
    video_post = VideoPost.query.get_or_404(id)
    if not video_post.is_calculated:
        tricks, ref_body, ref_legs, ref_grip = load_reference_data()
        pd_filepath = os.path.join(current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'pose_data_raw.csv')
        pd_savepath = os.path.join(current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'pose_data.csv')
        pd_results = process_pose_data(pd_filepath, pd_savepath, video_post, tricks, ref_body, ref_legs, ref_grip)        
        annotated_dir = os.path.join(current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'annotated')
        generate_timeline_image(annotated_dir, pd_results)        
        timeline_image = generate_timeline_image(annotated_dir, pd_results)
        
        if timeline_image:
            print("timeline image generated")
            
        if pd_results is None:
            flash("Something went wrong")
            return redirect(url_for('diary.all_dance_entries'))
        else:
            return redirect(url_for('reports.overview', id=video_post.id))
    else:
        video_report = VideoReport.query.filter_by(video_id=video_post.id, author_id=video_post.author_id).first()
        
        if video_post.report_id is None:
            video_post.report_id = video_report.id
            db.session.commit()
        
        if not video_report:
            flash("Report not found")
            return redirect(url_for('diary.all_dance_entries'))

        pd_filepath = os.path.join(
            current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'pose_data.csv')
        with open(pd_filepath, 'r') as file:
            pd_results = pd.read_csv(file)
        
        filter = pd_results[['image_filename','secs','frame_no','pos_face','pos_body','pos_legs','pos_grip','pos_trick']]
        pd_data = filter.to_dict(orient='records')
        
    fig_timeline = plotly_visualize_timeline(pd_results, video_report.created_on, video_report, 0.12)
    fig_plot = json.dumps(fig_timeline, cls=plotly.utils.PlotlyJSONEncoder)

    

    return render_template("reports/checker.html", title=f"{video_post.title}",
                           video_post=video_post,
                           pd_data=pd_data,
                           video_report=video_report,
                           fig_plot=fig_plot,
                           pd_filepath=pd_filepath,
                           )

@bp.route("/<id>/animation", methods=["GET", "POST"])
@login_required
def vis_animation(id):
    video_post = VideoPost.query.get_or_404(id)
    pd_filepath = os.path.join(
        current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'pose_data.csv')
    data = pd.read_csv(pd_filepath)
    fig = plotly_dynamic_pose_figure(data, right_arm=True,left_arm=True, right_leg=True, left_leg=True)
    fig_render = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)

    return render_template("reports/simple_plot.html",
                           title=f"{video_post.title}",
                           description="Visualize your dance moves as simple shapes to easily spot patterns and improve your technique",
                           fig_render=fig_render,
                           video_post=video_post)


@bp.route("/<id>/motion", methods=["GET", "POST"])
@login_required
def vis_range_of_motion(id):
    video_post = VideoPost.query.get_or_404(id)
    pd_filepath = os.path.join(
        current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'pose_data.csv')
    data = pd.read_csv(pd_filepath)
    fig = plot_polar_angles(data)
    fig_render = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)

    return render_template("reports/simple_plot.html",
                           title=f"{video_post.title}",

app/templates/reports/checker.html
{% extends '_base_checker.html' %}
{% block content %}


<div class="row text-start">

    <p class="mt-5">
        <a href="{{ url_for('diary.all_dance_entries') }}"
            class="badge align-items-center p-1 pe-2 text-secondary-emphasis bg-secondary-subtle border border-secondary-subtle rounded-pill"
            style="text-decoration: none;">
            ⬅️ Back to Home</a>
    </p>

    <h2 class="mb-3 text-start">
        <a href="{{ url_for('reports.overview', id=video_post.id) }}" class="link-primary"
            style="text-decoration: none;">{{
            title }}</a>
    </h2>
    <p>{{ video_post.created_on.strftime('%B %d, %Y') }} | {{ video_post.duration | round(2) }} seconds | {{
        video_report.spin_count
        }} spins 🌀 |
        {{video_report.inversion_count }}
        inversions 🙃 </p>
    <p> <a href="{{ url_for('reports.vis_animation', id=video_post.id) }}" class="btn btn-sm btn-outline-secondary">
            View Animation
        </a>

        <a href="{{ url_for('reports.vis_range_of_motion', id=video_post.id) }}"
            class="btn btn-sm btn-outline-secondary">
            View Range of Motion
        </a>

        <a href="{{ url_for('api.serve_uploaded_video', id=video_post.id, author_id=video_post.author_id ) }}"
            class="btn btn-sm btn-outline-secondary">
            View Reel
        </a>
        <a href="{{ url_for('diary.update_dance_entry', id=video_post.id) }}" class="btn btn-sm btn-outline-secondary">
            Edit This Entry
        </a>
    </p>
   

    <div class="col-md-12 my-3">
        <div class="table-responsive small">
            {% if pd_data %}
            <table class="table table-striped table-sm">
                <thead>
                    <tr>

                        <th>#</th>
                        <th>Image filename</th>
                        <th>Body</th>
                        <th>Face</th>
                        <th>Legs</th>
                        <th>Grip</th>
                        <th>Trick</th>

                    </tr>
                </thead>
                <tbody>

                    {% for row in pd_data %}
                    <tr>
                        <td>{{ loop.index -1 }}</td>
                        <td>
                        <img src="{{ url_for('api.serve_annotated_frame_img', author_id=current_user.id, id=video_post.id, image_filename=row['image_filename']) }}" class="img-fluid">
                            </td>
                        <td>{{ row['pos_body'] }}</td>
                        <td>{{ row['pos_face'] }}</td>
                        <td><a href="{{ url_for('dictionary.pose_legs_search') }}?q={{ row['pos_legs'] }}"
                                class="badge align-items-center p-1 pe-2 text-info-emphasis bg-info-subtle border border-info-subtle rounded-pill">
                                {{ row['pos_legs'] }}</a>
                        </td>
                        <td><a href="{{ url_for('dictionary.pose_grip_search') }}?q={{ row['pos_grip'] }}"
                                class="badge align-items-center p-1 pe-2 text-info-emphasis bg-info-subtle border border-info-subtle rounded-pill">
                                {{ row['pos_grip'] }}</a>
                        </td>

                        <td>
                            
                    
                            
                            <a href="{{ url_for('dictionary.pose_search') }}?q={{ row['pos_trick'] }}"
                                class="badge align-items-center p-1 pe-2 text-info-emphasis bg-info-subtle border border-info-subtle rounded-pill" target="_blank">
                                {{ row['pos_trick'] }}</a>
                        </td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}

        </div>


    </div>


    {% endblock %}

app/templates/reports/simple_plot.html
{% extends '_base.html' %}
{% block content %}
<div class="row text-start">

    <p class="mt-5">
      <a href="{{ url_for('reports.overview', id=video_post.id) }}"
        class="badge align-items-center p-1 pe-2 text-secondary-emphasis bg-secondary-subtle border border-secondary-subtle rounded-pill"
        style="text-decoration: none;">
        ⬅️ Back to Report Overview</a>
    </p>
    <h2 class="mb-3 text-start">
        <a href="{{ url_for('reports.overview', id=video_post.id) }}" class="link-primary" style="text-decoration: none;">{{
          title }}</a>
      </h2>
  

  
  <hr />
<p class="text-start">{{ description }}</p>
<div class="col-md-12">
  <div class="border">
      <div id="fig_render"></div>
      <script>
          var fig_render = {{ fig_render | safe }};
          Plotly.newPlot('fig_render', fig_render);

          function resizePlot() {
                var graphContainer = document.getElementById('fig_render');
                var width = graphContainer.offsetWidth; // Get the current width
                var update = {
                    height: width // Set height equal to width
                };
                Plotly.relayout('fig_render', update);
            }
            window.onload = resizePlot;
            window.onresize = resizePlot;
      </script>
  </div>
</div>
{% endblock %}