app/models/report.py
from app import db
import uuid
from datetime import datetime, timedelta

class VideoReport(db.Model):
    __tablename__ = 'reports'
    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    author_id = db.Column(db.String(36), db.ForeignKey('users.id'), nullable=False)
    video_id = db.Column(db.String(36), db.ForeignKey('videos.id'), nullable=False)
    spin_count = db.Column(db.String(100))
    inversion_count = db.Column(db.String(1000), nullable=True)
    detected_tricks = db.Column(db.String(1000), nullable=True)
    detected_grip = db.Column(db.String(1000), nullable=True)
    detected_legs = db.Column(db.String(1000), nullable=True)
    created_on = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    deleted = db.Column(db.Boolean, default=False)
    deleted_on = db.Column(db.DateTime, nullable=True)
    scheduled_for_deletion_on = db.Column(db.DateTime, nullable=True)
    video_post = db.relationship('VideoPost', foreign_keys=[video_id], backref='reports', lazy=True)

    def __repr__(self):
        return '<Report {}>'.format(self.id)
    

app/accounts/routes.py
from flask import Blueprint, flash, redirect, render_template, url_for, session, request
from flask_login import LoginManager, login_required, logout_user, current_user, login_user
from werkzeug.security import generate_password_hash, check_password_hash

from app import db
from app.models.user import User
from .forms import SignInForm, SignUpForm, EditAccountForm
import pytz

from datetime import datetime

bp = Blueprint("accounts", __name__, url_prefix="/accounts")
tz = pytz.timezone('UTC')

login_manager = LoginManager()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

@login_manager.unauthorized_handler
def unauthorized():
    flash("You must be logged in to view that page.")
    return redirect(url_for("accounts.sign_in"))

@bp.route("/sign-in", methods=["GET", "POST"])
def sign_in():
    form = SignInForm()
    if current_user.is_authenticated:
        return redirect(url_for('diary.all_dance_entries'))

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password_hash, form.password.data):
            user.last_login_on = tz.localize(datetime.utcnow())
            db.session.commit()
            login_user(user, remember=form.remember_me.data)
            return redirect(url_for('accounts.profile'))
        else:
            flash('Invalid email or password')

    return render_template("form.html", form=form, title="Sign In")

@bp.route("/sign-up", methods=["GET", "POST"])
def sign_up():
    form = SignUpForm()
    if current_user.is_authenticated:
        return redirect(url_for("diary.all_dance_entries"))

    if form.validate_on_submit():
        user = User.query.filter((User.username == form.username.data) | (User.email == form.email.data)).first()
        if user:
            print("user exists!")
            flash('Username or email already exists', 'error')
            return render_template("form.html", form=form, title="Sign Up")
        hashed_password = generate_password_hash(form.password.data)
        new_user = User(
            username=form.username.data,
            email=form.email.data,
            password_hash=hashed_password)
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)

        flash('Registration successful', 'success')
        return redirect(url_for('accounts.profile'))

    return render_template("form.html", form=form, title="Sign Up")

@bp.route("/sign-out")
@login_required
def sign_out():
    session.clear()
    logout_user()
    return redirect(url_for('accounts.sign_in'))

@bp.route("/profile", methods=["GET", "POST"], endpoint="profile")
@login_required
def profile():
    form = EditAccountForm()
    user = current_user
    if request.method == 'GET':
        form.deactivation.data = user.deleted

    if form.validate_on_submit():
        user = current_user
        
        if form.deactivation.data:
            if not user.deleted or datetime.utcnow() < user.scheduled_for_deletion_on:
                user.delete_user() 
        else:
            if user.deleted and datetime.utcnow() < user.scheduled_for_deletion_on:
                user.deleted = False
                user.deleted_on = None
                user.scheduled_for_deletion_on = None
        
        if form.password.data and form.password.data == form.password2.data:
            #salt = bcrypt.gensalt()
            #hashed_password = bcrypt.hashpw(form.password.data.encode('utf-8'), salt).decode('utf-8')
            user.password_hash = form.password.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('accounts.profile'))

    return render_template("form.html", form=form, title="Edit Account")

app/api/routes.py
from flask import Blueprint, send_from_directory, current_app, render_template, send_from_directory, redirect, url_for
from flask_login import login_required, current_user
import os
import pandas as pd
import pytz


bp = Blueprint("api", __name__, url_prefix="/api/v1/")
tz = pytz.timezone('UTC')

@bp.route('/uploads/<author_id>/<id>')
@login_required
def serve_uploaded_video(author_id,id):
    filename = f'{id}.mp4'
    filepath = os.path.join(current_app.config['SERVE_UPLOAD_FOLDER'],author_id)
    return send_from_directory(filepath,filename)

@bp.route('/dictionary/<category>')
@login_required
def serve_static_dictionary_tricks(category):
    if category == 'tricks':
        dict_read = pd.read_csv(os.path.join('app','static', 'dictionary', 'tricks', 'pose_data.csv'))
        dict_data = dict_read.to_dict(orient='records')
    elif category == 'legs':
        dict_read = pd.read_csv(os.path.join('app','static', 'dictionary', 'positions','legs', 'pose_data.csv'))
        dict_data = dict_read.to_dict(orient='records')
    elif category == 'body':
        dict_read = pd.read_csv(os.path.join('app','static', 'dictionary', 'positions','body', 'pose_data.csv'))
        dict_data = dict_read.to_dict(orient='records')
    elif category == 'grip':
        dict_read = pd.read_csv(os.path.join('app','static', 'dictionary', 'positions','grip', 'pose_data.csv'))
        dict_data = dict_read.to_dict(orient='records')
    else:
        return redirect(url_for('diary.all_dance_entries'))
    return dict_data

@bp.route('/processed/<author_id>/<id>')
@login_required
def serve_video_cover_page(author_id,id):
    if current_user.is_authenticated and current_user.id == author_id:
        filename = '0000_00000000.png'
        filepath = os.path.join(current_app.config['SERVE_PROCESSED_FOLDER'],author_id,id,'annotated')
        return send_from_directory(filepath,filename)
    

@bp.route('/processed/<author_id>/<id>/timeline')
@login_required
def serve_timeline_image(author_id,id):
    if current_user.is_authenticated and current_user.id == author_id:
        filename = 'timeline.png'
        filepath = os.path.join(current_app.config['SERVE_PROCESSED_FOLDER'],author_id,id,'annotated')
        return send_from_directory(filepath,filename)
    
@bp.route('/processed/<author_id>/<id>/<image_filename>')
@login_required
def serve_annotated_frame_img(author_id,id, image_filename):
    if current_user.is_authenticated and current_user.id == author_id:
        filepath = os.path.join(current_app.config['SERVE_PROCESSED_FOLDER'],author_id,id,'annotated')
        return send_from_directory(filepath,image_filename)
               

@bp.route('/pdata/<author_id>/<id>')
@login_required
def serve_pose_data(author_id,id):
    if current_user.is_authenticated and current_user.id == author_id:
        filename = 'pose_data.csv'
        filepath = os.path.join(current_app.config['SERVE_PROCESSED_FOLDER'],author_id,id)
        return send_from_directory(filepath,filename)

app/reports/routes.py
from flask import Blueprint, render_template, current_app, flash, redirect, url_for
from flask_login import login_required, current_user

from app.extensions.db import db
from app.extensions.plotly_visualizations import generate_histogram_chart, generate_histogram_chart_horizontal
from app.extensions.plotly_pose_animation import plotly_dynamic_pose_figure
from app.extensions.plotly_polar_plot import plot_polar_angles
from app.extensions.plotly_dance_timeline import plotly_visualize_timeline
from app.models import VideoPost, VideoReport
from app.services.pose_dimension_calculator import PoseDimensionCalculator
from app.services.pose_spatial_classifier import PoseSpatialClassifier
from app.services.pose_sequence_analyzer import PoseSequenceAnalyzer
from app.extensions.generate_timeline_visual import generate_timeline_image
from app.utilities.static_files import load_reference_data

import os
from datetime import datetime
import json
import pandas as pd
import plotly
import plotly.express as px
import pytz

bp = Blueprint("reports", __name__, url_prefix="/reports")
tz = pytz.timezone('UTC')

def process_pose_data(source_path, save_path, video_post, tricks, ref_body, ref_legs, ref_grip):
    with open(source_path, 'r') as file:
        pd_read = pd.read_csv(file)
    pd_calculated = PoseDimensionCalculator(pd_read, is_video=True)
    pd_classified = PoseSpatialClassifier(
        pd_calculated.data, ref_body, ref_legs, ref_grip)
    results = PoseSequenceAnalyzer(pd_classified.data, tricks)
    pd_results = results.data
    print("inversion count", results.inversion_count)

    if len(pd_results) > 0:
        pd_results.to_csv(save_path, index=False)
        video_post.is_calculated = True

        top_tricks = pd_results[pd_results['pos_trick'] != 'undefined']['pos_trick'].value_counts().nlargest(3).index.tolist()
        top_legs = pd_results[pd_results['pos_legs'] != 'undefined']['pos_legs'].value_counts().nlargest(3).index.tolist()
        top_grip = pd_results[pd_results['pos_grip'] != 'undefined']['pos_grip'].value_counts().nlargest(3).index.tolist()

        new_report = VideoReport(
            author_id=video_post.author_id,
            video_id=video_post.id,
            spin_count=str(results.spin_count),
            inversion_count=str(results.inversion_count),
            detected_tricks=','.join(top_tricks),
            detected_legs=','.join(top_legs),
            detected_grip=','.join(top_grip),
            created_on=datetime.utcnow()
        )

        db.session.add(video_post)
        db.session.add(new_report)
        db.session.commit()

        return pd_results
    else:
        return None


@bp.route("/<id>/", methods=["GET", "POST"])
@login_required
def overview(id):
    video_post = VideoPost.query.get_or_404(id)
    if not video_post.is_calculated:
        tricks, ref_body, ref_legs, ref_grip = load_reference_data()
        pd_filepath = os.path.join(current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'pose_data_raw.csv')
        pd_savepath = os.path.join(current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'pose_data.csv')
        pd_results = process_pose_data(pd_filepath, pd_savepath, video_post, tricks, ref_body, ref_legs, ref_grip)        
        annotated_dir = os.path.join(current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'annotated')
        generate_timeline_image(annotated_dir, pd_results)        
        timeline_image = generate_timeline_image(annotated_dir, pd_results)
        
        if timeline_image:
            print("timeline image generated")
            
        if pd_results is None:
            flash("Something went wrong")
            return redirect(url_for('diary.all_dance_entries'))
        else:
            return redirect(url_for('reports.overview', id=video_post.id))
    else:
        video_report = VideoReport.query.filter_by(video_id=video_post.id, author_id=video_post.author_id).first()
        
        if video_post.report_id is None:
            video_post.report_id = video_report.id
            db.session.commit()
        
        if not video_report:
            flash("Report not found")
            return redirect(url_for('diary.all_dance_entries'))

        pd_filepath = os.path.join(
            current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'pose_data.csv')
        with open(pd_filepath, 'r') as file:
            pd_results = pd.read_csv(file)
            
    fig_timeline = plotly_visualize_timeline(pd_results, video_report.created_on, video_report, 0.12)
    fig_plot = json.dumps(fig_timeline, cls=plotly.utils.PlotlyJSONEncoder)

    pd_data = pd_results.to_dict(orient='records')

    return render_template("report.html", title=f"{video_post.title}",
                           video_post=video_post,
                           pd_data=pd_data,
                           video_report=video_report,
                           fig_plot=fig_plot,
                           pd_filepath=pd_filepath
                           )


def generate_charts(pd_results, duration):
    fig_body = generate_histogram_chart(pd_results, 'pos_body', duration)
    fig_body_hbar = json.dumps(fig_body, cls=plotly.utils.PlotlyJSONEncoder)
    fig_grip = generate_histogram_chart_horizontal(
        pd_results, 'pos_grip', duration)
    fig_grip_hbar = json.dumps(fig_grip, cls=plotly.utils.PlotlyJSONEncoder)
    fig_legs = generate_histogram_chart_horizontal(
        pd_results, 'pos_legs', duration)
    fig_legs_hbar = json.dumps(fig_legs, cls=plotly.utils.PlotlyJSONEncoder)
    fig_tricks = generate_histogram_chart_horizontal(
        pd_results, 'pos_trick', duration)
    fig_tricks_hbar = json.dumps(
        fig_tricks, cls=plotly.utils.PlotlyJSONEncoder)

    return {
        'fig_body_hbar': fig_body_hbar,
        'fig_legs_hbar': fig_legs_hbar,
        'fig_grip_hbar': fig_grip_hbar,
        'fig_tricks_hbar': fig_tricks_hbar
    }


@bp.route("/<id>/checker", methods=["GET", "POST"])
@login_required
def report_checker(id):
    video_post = VideoPost.query.get_or_404(id)
    if not video_post.is_calculated:
        tricks, ref_body, ref_legs, ref_grip = load_reference_data()
        pd_filepath = os.path.join(current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'pose_data_raw.csv')
        pd_savepath = os.path.join(current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'pose_data.csv')
        pd_results = process_pose_data(pd_filepath, pd_savepath, video_post, tricks, ref_body, ref_legs, ref_grip)        
        annotated_dir = os.path.join(current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'annotated')
        generate_timeline_image(annotated_dir, pd_results)        
        timeline_image = generate_timeline_image(annotated_dir, pd_results)
        
        if timeline_image:
            print("timeline image generated")
            
        if pd_results is None:
            flash("Something went wrong")
            return redirect(url_for('diary.all_dance_entries'))
        else:
            return redirect(url_for('reports.overview', id=video_post.id))
    else:
        video_report = VideoReport.query.filter_by(video_id=video_post.id, author_id=video_post.author_id).first()
        
        if video_post.report_id is None:
            video_post.report_id = video_report.id
            db.session.commit()
        
        if not video_report:
            flash("Report not found")
            return redirect(url_for('diary.all_dance_entries'))

        pd_filepath = os.path.join(
            current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'pose_data.csv')
        with open(pd_filepath, 'r') as file:
            pd_results = pd.read_csv(file)
        
        filter = pd_results[['image_filename','secs','frame_no','pos_face','pos_body','pos_legs','pos_grip','pos_trick']]
        pd_data = filter.to_dict(orient='records')
        
    fig_timeline = plotly_visualize_timeline(pd_results, video_report.created_on, video_report, 0.12)
    fig_plot = json.dumps(fig_timeline, cls=plotly.utils.PlotlyJSONEncoder)

    

    return render_template("reports/checker.html", title=f"{video_post.title}",
                           video_post=video_post,
                           pd_data=pd_data,
                           video_report=video_report,
                           fig_plot=fig_plot,
                           pd_filepath=pd_filepath,
                           )

@bp.route("/<id>/animation", methods=["GET", "POST"])
@login_required
def vis_animation(id):
    video_post = VideoPost.query.get_or_404(id)
    pd_filepath = os.path.join(
        current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'pose_data.csv')
    data = pd.read_csv(pd_filepath)
    fig = plotly_dynamic_pose_figure(data, right_arm=True,left_arm=True, right_leg=True, left_leg=True)
    fig_render = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)

    return render_template("reports/simple_plot.html",
                           title=f"{video_post.title}",
                           description="Visualize your dance moves as simple shapes to easily spot patterns and improve your technique",
                           fig_render=fig_render,
                           video_post=video_post)


@bp.route("/<id>/motion", methods=["GET", "POST"])
@login_required
def vis_range_of_motion(id):
    video_post = VideoPost.query.get_or_404(id)
    pd_filepath = os.path.join(
        current_app.config['FRAME_OUTPUT_FOLDER'], video_post.author_id, video_post.id, 'pose_data.csv')
    data = pd.read_csv(pd_filepath)
    fig = plot_polar_angles(data)
    fig_render = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)

    return render_template("reports/simple_plot.html",
                           title=f"{video_post.title}",

app/templates/_base.html
<!doctype html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>poledance.xyz</title>
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">

    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>

    <link href="{{ url_for('static', filename='css/cover.css') }}" rel="stylesheet">
</head>

<body class="d-flex h-100 text-center text-black bg-light">

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="mb-auto">
            <div>
                <h3 class="float-md-start mb-0">poledance.xyz</h3>
                <nav class="nav nav-masthead justify-content-center float-md-end">
                    <a class="nav-link link-secondary" aria-current="page"
                        href="{{ url_for('dictionary.pose_search') }}">Search Pose</a>
                    {% if current_user.is_authenticated %}
                    <a class="nav-link link-secondary" href="{{ url_for('diary.all_dance_entries') }}">Diary</a>
                    <a class="nav-link link-secondary" href="{{ url_for('accounts.sign_out') }}">Log Out</a>
                    {% else %}
                    <a class="nav-link link-secondary" href="{{ url_for('accounts.sign_up') }}">Register</a>
                    <a class="nav-link link-secondary" href="{{ url_for('accounts.sign_in') }}">Login</a>
                    {% endif %}
                </nav>
            </div>
        </header>

        <main class="">

            {% block content %}{% endblock %}

        </main>

        {% include "_footer.html" %}
    </div>

    {{ moment.include_moment() }}

</body>

</html>

app/templates/_base_checker.html
<!doctype html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>poledance.xyz</title>
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">

    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>

    <link href="{{ url_for('static', filename='css/cover.css') }}" rel="stylesheet">
</head>

<body class="d-flex h-100 text-center text-black bg-light">

    <div class="container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="mb-auto">
            <div>
                <h3 class="float-md-start mb-0">poledance.xyz</h3>
                <nav class="nav nav-masthead justify-content-center float-md-end">
                    <a class="nav-link link-secondary" aria-current="page"
                        href="{{ url_for('dictionary.pose_search') }}">Search Pose</a>
                    {% if current_user.is_authenticated %}
                    <a class="nav-link link-secondary" href="{{ url_for('diary.all_dance_entries') }}">Diary</a>
                    <a class="nav-link link-secondary" href="{{ url_for('accounts.sign_out') }}">Log Out</a>
                    {% else %}
                    <a class="nav-link link-secondary" href="{{ url_for('accounts.sign_up') }}">Register</a>
                    <a class="nav-link link-secondary" href="{{ url_for('accounts.sign_in') }}">Login</a>
                    {% endif %}
                </nav>
            </div>
        </header>

        <main class="">

            {% block content %}{% endblock %}

        </main>

        {% include "_footer.html" %}
    </div>

    {{ moment.include_moment() }}

</body>

</html>

app/templates/_footer.html
<hr class="mt-5" />

<footer class="py-5">
    <p class="muted"><small><i>

                <b>PoledanceXYZ</b>, crafted with a blend of data science and a love for pole dance, is presently in
                beta mode. As such, it's possible for the application to encounter errors or deliver unexpected
                outcomes. We welcome your feedback and encourage reporting any issues. For more information,
                feel free to contact <a href="https://github.com/kayesokua" class="text-primary">@kayesokua</a> and
                explore our documentation <a href="https://github.com/kayesokua/poledance.xyz/tree/main/docs"
                    class="text-primary">here</a>.
            </i>


    </p>

</footer>

app/templates/profile.html
{% extends '_base.html' %}
{% block content %}
<h1>Welcome back! {{ current_user.username }}</h1>
<p class="lead">
    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
</p>
<p class="lead">
    <a href="{{ url_for('diary.new_dance_entry') }}" class="btn btn-lg btn-primary fw-bold text-white">Upload New
        Dance</a>

    <a href="{{ url_for('accounts.sign_out') }}" class="btn btn-lg btn-secondary fw-bold text-white bg-dark">Sign
        Out</a>
</p>
{% endblock %}

app/templates/report.html
{% extends '_base.html' %}
{% block content %}


<div class="row text-start">

  <p class="mt-5">
    <a href="{{ url_for('diary.all_dance_entries') }}"
      class="badge align-items-center p-1 pe-2 text-secondary-emphasis bg-secondary-subtle border border-secondary-subtle rounded-pill"
      style="text-decoration: none;">
      ⬅️ Back to Home</a>
  </p>

  <h2 class="mb-3 text-start">
    <a href="{{ url_for('reports.overview', id=video_post.id) }}" class="link-primary" style="text-decoration: none;">{{
      title }}</a>
  </h2>
  <p>{{ video_post.created_on.strftime('%B %d, %Y') }} | {{ video_post.duration | round(2) }} seconds | {{ video_report.spin_count
    }} spins 🌀 |
    {{video_report.inversion_count }}
    inversions 🙃 </p>
  <p> <a href="{{ url_for('reports.vis_animation', id=video_post.id) }}" class="btn btn-sm btn-outline-secondary">
      View Animation
    </a>

    <a href="{{ url_for('reports.vis_range_of_motion', id=video_post.id) }}" class="btn btn-sm btn-outline-secondary">
      View Range of Motion
    </a>

    <a href="{{ url_for('reports.report_checker', id=video_post.id) }}" class="btn btn-sm btn-outline-secondary">
      Checker
    </a>

    <a href="{{ url_for('api.serve_uploaded_video', id=video_post.id, author_id=video_post.author_id ) }}"
      class="btn btn-sm btn-outline-secondary">
      View Reel
    </a>
    <a href="{{ url_for('diary.update_dance_entry', id=video_post.id) }}" class="btn btn-sm btn-outline-secondary">
      Edit This Entry
    </a>
  </p>
  <div class="col-12 mb-3">
    <div style="overflow-x: auto; border: 1px solid #dee2e6;">
        <img src="{{ url_for('api.serve_timeline_image', id=video_post.id, author_id=video_post.author_id ) }}" 
             style="max-height: 250px; width: auto; display: block;"/>
    </div>
</div>

<div class="col-md-12 my-3">
  <div class="table-responsive small">
      <table class="table table-striped table-sm" style="font-size: x-small;">
          <thead>
              <tr>
                  {% if pose_world_data %}
                  {% for key in pose_world_data[0] %}
                  <th>{{ key }}</th>
                  {% endfor %}
                  {% endif %}
              </tr>
          </thead>
          <tbody>
              {% for row in pose_world_data %}
              <tr>

                  {% for value in row.values() %}
                  <td>{{ value }}</td>
                  {% endfor %}
              </tr>
              {% endfor %}
          </tbody>
      </table>
  </div>


  <div class="col-md-12 mb-3">
    <div style="overflow-y: scroll; border: 1px solid #dee2e6;">
      <div id="fig_plot" style="width:1200px; height: 350px"></div>
      <script>
        var fig_plot = {{ fig_plot | safe }};
        Plotly.newPlot('fig_plot', fig_plot);
      </script>
    </div>



  </div>

  <hr class="py-3" />
  <div class="col-12">
    <p class="mb-3"><b>About this Choreography</b></p>
    <p class="lead text-start mb-3">
      {{ video_post.description }}</p>


  </div>

</div>





<hr class="py-3" />

{% if video_report.detected_tricks %}
<p class="text-start muted"><b>Most detected poses</b><br />
  {% for trick in video_report.detected_tricks.split(',') %}
  <a href="{{ url_for('dictionary.pose_search') }}?q={{ trick }}"
    class="badge align-items-center p-1 pe-2 text-info-emphasis bg-info-subtle border border-info-subtle rounded-pill">
    {{ trick }}</a>
  {% endfor %}
</p>
{% endif %}

{% if video_report.detected_grip %}
<p class="text-start muted"><b>Most detected grip</b><br />
  {% for grip in video_report.detected_grip.split(',') %}
  <a href="{{ url_for('dictionary.pose_grip_search') }}?q={{ grip }}"
    class="badge align-items-center p-1 pe-2 text-info-emphasis bg-info-subtle border border-info-subtle rounded-pill">
    {{ grip }}</a>
  {% endfor %}
</p>
{% endif %}

{% if video_report.detected_legs %}
<p class="text-start muted"><b>Most detected grip</b><br />
  {% for legs in video_report.detected_legs.split(',') %}
  <a href="{{ url_for('dictionary.pose_legs_search') }}?q={{ legs }}"
    class="badge align-items-center p-1 pe-2 text-info-emphasis bg-info-subtle border border-info-subtle rounded-pill">
    {{ legs }}</a>
  {% endfor %}
</p>
{% endif %}
<p class="text-start muted mb-5"><b>Export Your Pose Data</b><br />

  <a href="{{ url_for('api.serve_pose_data', id=video_post.id, author_id=video_post.author_id ) }}"
    class="badge align-items-center p-1 pe-2 text-warning-emphasis bg-warning-subtle border border-warning-subtle rounded-pill">🍣
    Click Here to Download Your Raw Data (.csv) </a>
</p>


{% endblock %}